"""
Rule-based correction candidates.

The LLM should judge candidates, not construct offsets or replacements.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import List, Optional

from src.core.error_record import ErrorRecord
from src.core.text import TextDoc


@dataclass(frozen=True)
class CorrectionCandidate:
    """A concrete text replacement generated by deterministic rules."""

    candidate_id: str
    error_id: str
    error_type: str
    start_offset: int
    end_offset: int
    replacement: str
    description: str

    def original(self, text: TextDoc) -> str:
        return text.text[self.start_offset:self.end_offset]

    def preview(self, text: TextDoc, context: int = 30) -> dict:
        before_start = max(0, self.start_offset - context)
        after_end = min(len(text.text), self.end_offset + context)
        return {
            "candidate_id": self.candidate_id,
            "description": self.description,
            "start_offset": self.start_offset,
            "end_offset": self.end_offset,
            "original": text.text[self.start_offset:self.end_offset],
            "replacement": self.replacement,
            "before": text.text[before_start:self.start_offset],
            "after": text.text[self.end_offset:after_end],
        }


class CandidateGenerator:
    """Generate deterministic fix candidates for detector-produced errors."""

    _OPEN_TO_CLOSE = {
        "[": "]",
        "\u3010": "\u3011",  # 【】
        "\uff3b": "\uff3d",  # ［］
        "{": "}",
        "\u300a": "\u300b",  # 《》
        "\u201c": "\u201d",  # ""
        "\u2018": "\u2019",  # ''
        # Japanese-style white corner brackets
        "\u300e": "\u300f",  # 『』
        # Half-width variants
        "(": ")",
        "\uff1c": "\uff1e",  # ＜＞
        "\u3008": "\u3009",  # 〈〉
    }
    _CLOSE_TO_OPEN = {v: k for k, v in _OPEN_TO_CLOSE.items()}
    _WRONG_TO_STANDARD = {
        # Standard bracket types
        "[": "\u300c",       # [
        "\u3010": "\u300c",  # 【 → 「
        "\uff3b": "\u300c",  # ［ → 「
        "{": "\u300c",       # {
        "\u300a": "\u300c",  # 《 → 「
        "\u201c": "\u300c",  # " → 「
        "\u2018": "\u300c",  # ' → 「
        "]": "\u300d",       # ]
        "\u3011": "\u300d",  # 】 → 」
        "\uff3d": "\u300d",  # ］ → 」
        "}": "\u300d",       # }
        "\u300b": "\u300d",  # 》 → 」
        "\u201d": "\u300d",  # " → 」
        "\u2019": "\u300d",  # ' → 」
        # Japanese-style white corner brackets (most common remaining)
        "\u300e": "\u300c",  # 『 → 「
        "\u300f": "\u300d",  # 』 → 」
        # Half-width and other variants
        "(": "\u300c",       # ( → 「
        ")": "\u300d",       # ) → 」
        "\uff1c": "\u300c",  # ＜ → 「
        "\uff1e": "\u300d",  # ＞ → 」
        "\u3008": "\u300c",  # 〈 → 「
        "\u3009": "\u300d",  # 〉 → 」
    }
    _WRONG_DIALOGUE_CLOSERS = (
        "]", "\u3011", "\uff3d", "}", "\u300b", "\u201d", '"',
        "[", "\u3010", "\uff3b", "{", "\u300a", "\u201c",
        ")", "\uff1e", "\uff09", "\uff08",
    )
    _NARRATION_CUES = (
        "他", "她", "我", "你", "少年", "少女", "男人", "女人",
        "老师", "同学", "对方", "众人", "大家", "这", "那",
    )

    def generate(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        etype = error.error_type
        if etype == "wrong_symbol":
            return self._wrong_symbol(text, error)
        if etype == "consecutive":
            return self._consecutive(text, error)
        if etype == "unpaired":
            return self._unpaired(text, error)
        if etype == "missing_bracket":
            return self._missing_bracket(text, error)
        if etype == "long_dialogue":
            return self._long_dialogue(text, error)
        return []

    def _candidate(
        self,
        items: list[CorrectionCandidate],
        error: ErrorRecord,
        start: int,
        end: int,
        replacement: str,
        description: str,
    ) -> None:
        if start < 0 or end < start:
            return
        items.append(
            CorrectionCandidate(
                candidate_id=f"c{len(items) + 1}",
                error_id=error.error_id,
                error_type=error.error_type,
                start_offset=start,
                end_offset=end,
                replacement=replacement,
                description=description,
            )
        )

    def _resolve_offset(self, full: str, offset: int, target_set: set) -> int:
        """Scan forward from offset to find first character in target_set.
        Returns the found position, or -1 if not found within reasonable range.
        """
        end = min(len(full), offset + 20)
        for pos in range(offset, end):
            if full[pos] in target_set:
                return pos
        return -1

    def _wrong_symbol(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        full = text.text
        offset = error.offset
        if offset < 0 or offset >= len(full):
            return []

        # Scan forward to find the actual wrong symbol (offset may point to whitespace)
        resolved = self._resolve_offset(full, offset, set(self._WRONG_TO_STANDARD.keys()))
        if resolved == -1:
            return []
        offset = resolved
        ch = full[offset]
        candidates: list[CorrectionCandidate] = []

        # Strategy 1: Check for paired symbols
        pair = self._find_wrong_symbol_pair(full, offset, ch)
        if pair:
            start, end = pair
            inner = full[start + 1:end - 1]
            self._candidate(
                candidates,
                error,
                start,
                end,
                f"「{inner}」",
                "将成对的非标准包裹符号替换为「」",
            )

        # Strategy 2: Handle nested symbols like [text「text」text]
        # Look for mixed bracket patterns
        for open_ch, close_ch in self._OPEN_TO_CLOSE.items():
            if open_ch in ("「", "」"):
                continue
            # Search for open_ch before offset and close_ch after offset
            start_search = max(0, offset - 200)
            open_pos = full.rfind(open_ch, start_search, offset)
            if open_pos != -1:
                close_pos = full.find(close_ch, offset + 1, min(len(full), offset + 200))
                if close_pos != -1:
                    inner = full[open_pos + 1:close_pos]
                    self._candidate(
                        candidates,
                        error,
                        open_pos,
                        close_pos + 1,
                        f"「{inner}」",
                        f"将嵌套的非标准包裹符号 {open_ch}{close_ch} 替换为「」",
                    )

        # Strategy 3 (was 4): Handle cases where 「」 encloses wrong symbols like 「text[text]text」
        # The detector may flag the inner [ or ]
        # For now, skip these - they need LLM judgment to determine if the inner
        # symbol should be replaced or if the outer 「」 is wrong

        return self._dedupe(candidates)

    def _find_wrong_symbol_pair(
        self,
        text: str,
        offset: int,
        ch: str,
        window: int = 5000,
    ) -> Optional[tuple[int, int]]:
        if ch in self._OPEN_TO_CLOSE:
            closer = self._OPEN_TO_CLOSE[ch]
            close = text.find(closer, offset + 1, min(len(text), offset + window))
            if close != -1:
                return offset, close + 1
        opener = self._CLOSE_TO_OPEN.get(ch)
        if opener:
            start = max(0, offset - window)
            open_pos = text.rfind(opener, start, offset)
            if open_pos != -1:
                return open_pos, offset + 1
        return None

    def _consecutive(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        full = text.text
        offset = error.offset
        if offset < 0 or offset >= len(full):
            return []

        # Scan forward to find the actual bracket (offset may point to whitespace/newline)
        resolved = self._resolve_offset(full, offset, {"「", "」"})
        if resolved == -1:
            return []
        offset = resolved

        candidates: list[CorrectionCandidate] = []
        current = full[offset]
        opposite = "」" if current == "「" else "「"

        # Candidate 1: flip the symbol at offset
        self._candidate(
            candidates,
            error,
            offset,
            offset + 1,
            opposite,
            "替换当前连续符号，使「」交替",
        )

        # Candidate 2: flip the previous dialogue symbol (if same as current)
        previous = self._previous_dialogue_symbol(full, offset)
        if previous is not None and full[previous] == current:
            self._candidate(
                candidates,
                error,
                previous,
                previous + 1,
                opposite,
                "替换前一个连续符号，使「」交替",
            )

        # Candidate 3: if the consecutive is at the start of a line (after \n),
        # also try flipping the NEWLINE-adjacent bracket that precedes this one
        # Pattern: 」\n    「 → the 「 after \n is consecutive to the 」 before \n
        # Fix: flip the 「 to 」 (making it a closing bracket for the previous line)
        if current == "「":
            # Check if this 「 follows newline+whitespace after a previous 「 or 」
            # The consecutive detector only flags when same bracket type appears twice
            # So 「 after \n means the bracket before \n was also 「
            # Look for the dialogue symbol before the nearest newline
            for search_pos in range(offset - 1, max(0, offset - 100), -1):
                if full[search_pos] == "\n":
                    # Found newline, now look back for the bracket before it
                    pre_newline = self._previous_dialogue_symbol(full, search_pos)
                    if pre_newline is not None and full[pre_newline] == "「":
                        self._candidate(
                            candidates,
                            error,
                            pre_newline,
                            pre_newline + 1,
                            "」",
                            "将换行前的左引号「改为」以消除跨行连续",
                        )
                    break
                if full[search_pos] in ("「", "」"):
                    break

        return self._dedupe(candidates)

    @staticmethod
    def _previous_dialogue_symbol(text: str, offset: int) -> Optional[int]:
        for pos in range(offset - 1, -1, -1):
            if text[pos] in ("「", "」"):
                return pos
        return None

    def _unpaired(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        full = text.text
        offset = error.offset
        if offset < 0 or offset >= len(full):
            return []

        # Scan forward to find the actual bracket
        resolved = self._resolve_offset(full, offset, {"「", "」"})
        if resolved == -1:
            return []
        offset = resolved
        ch = full[offset]
        candidates: list[CorrectionCandidate] = []
        if ch == "」":
            self._candidate(candidates, error, offset, offset + 1, "", "删除多余的右引号」")
            self._candidate(candidates, error, offset, offset + 1, "「", "将多余的」改为左引号「")
        elif ch == "「":
            insert_at = self._line_end_offset(text, error.line_number)
            self._candidate(candidates, error, insert_at, insert_at, "」", "在本行末尾补上右引号」")
            self._candidate(candidates, error, offset, offset + 1, "", "删除未匹配的左引号「")
            self._candidate(candidates, error, offset, offset + 1, "」", "将未匹配的「改为右引号」")

        return self._dedupe(candidates)

    @staticmethod
    def _line_end_offset(text: TextDoc, line_number: int) -> int:
        start = text.line_to_offset(line_number)
        line = text[line_number]
        return start + len(line)

    def _missing_bracket(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        try:
            line = text[error.line_number]
            line_start = text.line_to_offset(error.line_number)
        except IndexError:
            return []

        candidates: list[CorrectionCandidate] = []
        colon_match = re.search(r"[：:]", line)
        if not colon_match:
            return candidates

        content_start = colon_match.end()
        while content_start < len(line) and line[content_start].isspace():
            content_start += 1
        if content_start >= len(line):
            return candidates

        content = line[content_start:]
        self._candidate(
            candidates,
            error,
            line_start + content_start,
            line_start + len(line),
            f"「{content}」",
            "将冒号后的台词包裹为「」",
        )
        return candidates

    def _long_dialogue(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        full = text.text
        start = error.offset
        if start < 0 or start >= len(full):
            return []

        # Scan forward to find the opening 「
        resolved = self._resolve_offset(full, start, {"「"})
        if resolved == -1:
            return []
        start = resolved

        close = full.find("」", start + 1)
        if close == -1:
            return []

        content_start = start + 1
        content = full[content_start:close]
        candidates: list[CorrectionCandidate] = []

        # Strategy 1: replace wrong closing symbols inside the dialogue
        for index, ch in enumerate(content):
            if ch not in self._WRONG_DIALOGUE_CLOSERS:
                continue
            self._candidate(
                candidates,
                error,
                content_start + index,
                content_start + index + 1,
                "」",
                f"将超长对话中疑似误识别的闭合符号 {ch!r} 替换为」",
            )
            if len(candidates) >= 3:
                break

        # Strategy 2: split on 。+ narration cues
        for match in re.finditer("。", content):
            cue_start = match.end()
            if not any(content.startswith(cue, cue_start) for cue in self._NARRATION_CUES):
                continue
            second_end = content.find("。", cue_start)
            if second_end == -1:
                continue
            second_end += 1
            segment = content[match.start():second_end]
            replacement = "。」" + segment[1:-1] + "。「"
            self._candidate(
                candidates,
                error,
                content_start + match.start(),
                content_start + second_end,
                replacement,
                "在疑似旁白段两侧补上」「以拆分超长对话",
            )
            if len(candidates) >= 3:
                break

        # Strategy 3: split on ？or ！or ……+ narration cues (for long dialogues without 。)
        if len(candidates) < 3:
            for boundary in ("？", "！", "……"):
                for match in re.finditer(re.escape(boundary), content):
                    cue_start = match.end()
                    # Check if what follows looks like narration (starts with known cue)
                    rest = content[cue_start:].lstrip()
                    if not any(rest.startswith(cue) for cue in self._NARRATION_CUES):
                        continue
                    self._candidate(
                        candidates,
                        error,
                        content_start + match.start(),
                        content_start + match.end(),
                        match.group() + "」",
                        f"在{boundary}后插入」以拆分超长对话",
                    )
                    if len(candidates) >= 3:
                        break

        # Strategy 4: if the long dialogue has \n\n + narration, insert 」before \n\n
        if len(candidates) < 2:
            nl_pos = content.find("\n\n")
            if nl_pos != -1:
                # Check if there's narration after \n\n
                after_nl = content[nl_pos + 2:].lstrip()
                if any(after_nl.startswith(cue) for cue in self._NARRATION_CUES):
                    self._candidate(
                        candidates,
                        error,
                        content_start + nl_pos,
                        content_start + nl_pos,
                        "」\n\n",
                        "在换行前插入」以分离旁白",
                    )

        # Strategy 5: split on 。 + any character that looks like narration start (not just known cues)
        # This handles cases where narration starts with a name or other indicator
        if len(candidates) < 3:
            for match in re.finditer("。", content):
                cue_start = match.end()
                rest = content[cue_start:].lstrip()
                if not rest:
                    continue
                # Heuristic: narration often starts with a name/pronoun or descriptive word
                # Check if rest starts with common narration patterns
                narration_starts = self._NARRATION_CUES + (
                    "却", "又", "却", "还", "便", "就", "只", "只见", "只听",
                    "忽", "蓦", "猛", "顿", "陡", "霍", "豁", "倏",
                )
                if any(rest.startswith(cue) for cue in narration_starts):
                    second_end = content.find("。", cue_start)
                    if second_end == -1:
                        continue
                    second_end += 1
                    segment = content[match.start():second_end]
                    replacement = "。」" + segment[1:-1] + "。「"
                    self._candidate(
                        candidates,
                        error,
                        content_start + match.start(),
                        content_start + second_end,
                        replacement,
                        "在疑似旁白段两侧补上」「以拆分超长对话(扩展触发词)",
                    )
                    if len(candidates) >= 3:
                        break

        # Strategy 6: Handle multiple consecutive segments - split at each 。+narration
        if len(candidates) < 2:
            # Try to find multiple split points
            splits = []
            for match in re.finditer("。", content):
                cue_start = match.end()
                rest = content[cue_start:].lstrip()
                if any(rest.startswith(cue) for cue in self._NARRATION_CUES):
                    second_end = content.find("。", cue_start)
                    if second_end != -1:
                        splits.append((match.start(), second_end + 1))
            if len(splits) >= 2:
                # Generate candidate that splits at first split point
                first_start, first_end = splits[0]
                segment = content[first_start:first_end]
                replacement = "。」" + segment[1:-1] + "。「"
                self._candidate(
                    candidates,
                    error,
                    content_start + first_start,
                    content_start + first_end,
                    replacement,
                    "在首个疑似旁白段两侧补上」「以拆分超长对话",
                )

        return self._dedupe(candidates)

    @staticmethod
    def _dedupe(candidates: List[CorrectionCandidate]) -> List[CorrectionCandidate]:
        seen: set[tuple[int, int, str]] = set()
        result: list[CorrectionCandidate] = []
        for candidate in candidates:
            key = (candidate.start_offset, candidate.end_offset, candidate.replacement)
            if key in seen:
                continue
            seen.add(key)
            result.append(
                CorrectionCandidate(
                    candidate_id=f"c{len(result) + 1}",
                    error_id=candidate.error_id,
                    error_type=candidate.error_type,
                    start_offset=candidate.start_offset,
                    end_offset=candidate.end_offset,
                    replacement=candidate.replacement,
                    description=candidate.description,
                )
            )
        return result
