"""
Rule-based correction candidates.

The LLM should judge candidates, not construct offsets or replacements.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import List, Optional

from src.core.error_record import ErrorRecord
from src.core.text import TextDoc


@dataclass(frozen=True)
class CorrectionCandidate:
    """A concrete text replacement generated by deterministic rules."""

    candidate_id: str
    error_id: str
    error_type: str
    start_offset: int
    end_offset: int
    replacement: str
    description: str

    def original(self, text: TextDoc) -> str:
        return text.text[self.start_offset:self.end_offset]

    def preview(self, text: TextDoc, context: int = 30) -> dict:
        before_start = max(0, self.start_offset - context)
        after_end = min(len(text.text), self.end_offset + context)
        return {
            "candidate_id": self.candidate_id,
            "description": self.description,
            "start_offset": self.start_offset,
            "end_offset": self.end_offset,
            "original": text.text[self.start_offset:self.end_offset],
            "replacement": self.replacement,
            "before": text.text[before_start:self.start_offset],
            "after": text.text[self.end_offset:after_end],
        }


class CandidateGenerator:
    """Generate deterministic fix candidates for detector-produced errors."""

    _OPEN_TO_CLOSE = {
        "[": "]",
        "【": "】",
        "［": "］",
        "{": "}",
        "《": "》",
        "“": "”",
        '"': '"',
    }
    _CLOSE_TO_OPEN = {v: k for k, v in _OPEN_TO_CLOSE.items()}
    _WRONG_TO_STANDARD = {
        "[": "「",
        "【": "「",
        "［": "「",
        "{": "「",
        "《": "「",
        "“": "「",
        '"': "「",
        "]": "」",
        "】": "」",
        "］": "」",
        "}": "」",
        "》": "」",
        "”": "」",
    }
    _WRONG_DIALOGUE_CLOSERS = (
        "]", "】", "］", "}", "》", "”", '"',
        "[", "【", "［", "{", "《", "“",
    )
    _NARRATION_CUES = (
        "他", "她", "我", "你", "少年", "少女", "男人", "女人",
        "老师", "同学", "对方", "众人", "大家", "这", "那",
    )

    def generate(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        etype = error.error_type
        if etype == "wrong_symbol":
            return self._wrong_symbol(text, error)
        if etype == "consecutive":
            return self._consecutive(text, error)
        if etype == "unpaired":
            return self._unpaired(text, error)
        if etype == "missing_bracket":
            return self._missing_bracket(text, error)
        if etype == "long_dialogue":
            return self._long_dialogue(text, error)
        return []

    def _candidate(
        self,
        items: list[CorrectionCandidate],
        error: ErrorRecord,
        start: int,
        end: int,
        replacement: str,
        description: str,
    ) -> None:
        if start < 0 or end < start:
            return
        items.append(
            CorrectionCandidate(
                candidate_id=f"c{len(items) + 1}",
                error_id=error.error_id,
                error_type=error.error_type,
                start_offset=start,
                end_offset=end,
                replacement=replacement,
                description=description,
            )
        )

    def _wrong_symbol(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        full = text.text
        offset = error.offset
        if offset < 0 or offset >= len(full):
            return []

        ch = full[offset]
        candidates: list[CorrectionCandidate] = []

        pair = self._find_wrong_symbol_pair(full, offset, ch)
        if pair:
            start, end = pair
            inner = full[start + 1:end - 1]
            self._candidate(
                candidates,
                error,
                start,
                end,
                f"「{inner}」",
                "将成对的非标准包裹符号替换为「」",
            )

        mapped = self._WRONG_TO_STANDARD.get(ch)
        if mapped:
            self._candidate(
                candidates,
                error,
                offset,
                offset + 1,
                mapped,
                f"将单个非标准符号 {ch!r} 替换为 {mapped!r}",
            )

        return self._dedupe(candidates)

    def _find_wrong_symbol_pair(
        self,
        text: str,
        offset: int,
        ch: str,
        window: int = 240,
    ) -> Optional[tuple[int, int]]:
        if ch in self._OPEN_TO_CLOSE:
            closer = self._OPEN_TO_CLOSE[ch]
            close = text.find(closer, offset + 1, min(len(text), offset + window))
            if close != -1:
                return offset, close + 1
        opener = self._CLOSE_TO_OPEN.get(ch)
        if opener:
            start = max(0, offset - window)
            open_pos = text.rfind(opener, start, offset)
            if open_pos != -1:
                return open_pos, offset + 1
        return None

    def _consecutive(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        full = text.text
        offset = error.offset
        if offset < 0 or offset >= len(full) or full[offset] not in ("「", "」"):
            return []

        candidates: list[CorrectionCandidate] = []
        current = full[offset]
        opposite = "」" if current == "「" else "「"
        self._candidate(
            candidates,
            error,
            offset,
            offset + 1,
            opposite,
            "替换当前连续符号，使「」交替",
        )

        previous = self._previous_dialogue_symbol(full, offset)
        if previous is not None and full[previous] == current:
            self._candidate(
                candidates,
                error,
                previous,
                previous + 1,
                opposite,
                "替换前一个连续符号，使「」交替",
            )

        return self._dedupe(candidates)

    @staticmethod
    def _previous_dialogue_symbol(text: str, offset: int) -> Optional[int]:
        for pos in range(offset - 1, -1, -1):
            if text[pos] in ("「", "」"):
                return pos
        return None

    def _unpaired(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        full = text.text
        offset = error.offset
        if offset < 0 or offset >= len(full):
            return []

        ch = full[offset]
        candidates: list[CorrectionCandidate] = []
        if ch == "」":
            self._candidate(candidates, error, offset, offset + 1, "", "删除多余的右引号」")
            self._candidate(candidates, error, offset, offset + 1, "「", "将多余的」改为左引号「")
        elif ch == "「":
            insert_at = self._line_end_offset(text, error.line_number)
            self._candidate(candidates, error, insert_at, insert_at, "」", "在本行末尾补上右引号」")
            self._candidate(candidates, error, offset, offset + 1, "", "删除未匹配的左引号「")
            self._candidate(candidates, error, offset, offset + 1, "」", "将未匹配的「改为右引号」")

        return self._dedupe(candidates)

    @staticmethod
    def _line_end_offset(text: TextDoc, line_number: int) -> int:
        start = text.line_to_offset(line_number)
        line = text[line_number]
        return start + len(line)

    def _missing_bracket(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        try:
            line = text[error.line_number]
            line_start = text.line_to_offset(error.line_number)
        except IndexError:
            return []

        candidates: list[CorrectionCandidate] = []
        colon_match = re.search(r"[：:]", line)
        if not colon_match:
            return candidates

        content_start = colon_match.end()
        while content_start < len(line) and line[content_start].isspace():
            content_start += 1
        if content_start >= len(line):
            return candidates

        content = line[content_start:]
        self._candidate(
            candidates,
            error,
            line_start + content_start,
            line_start + len(line),
            f"「{content}」",
            "将冒号后的台词包裹为「」",
        )
        return candidates

    def _long_dialogue(self, text: TextDoc, error: ErrorRecord) -> List[CorrectionCandidate]:
        full = text.text
        start = error.offset
        if start < 0 or start >= len(full) or full[start] != "「":
            return []

        close = full.find("」", start + 1)
        if close == -1:
            return []

        content_start = start + 1
        content = full[content_start:close]
        candidates: list[CorrectionCandidate] = []

        for index, ch in enumerate(content):
            if ch not in self._WRONG_DIALOGUE_CLOSERS:
                continue
            self._candidate(
                candidates,
                error,
                content_start + index,
                content_start + index + 1,
                "」",
                f"将超长对话中疑似误识别的闭合符号 {ch!r} 替换为」",
            )
            if len(candidates) >= 3:
                break

        for match in re.finditer("。", content):
            cue_start = match.end()
            if not any(content.startswith(cue, cue_start) for cue in self._NARRATION_CUES):
                continue
            second_end = content.find("。", cue_start)
            if second_end == -1:
                continue
            second_end += 1
            segment = content[match.start():second_end]
            replacement = "。」" + segment[1:-1] + "。「"
            self._candidate(
                candidates,
                error,
                content_start + match.start(),
                content_start + second_end,
                replacement,
                "在疑似旁白段两侧补上」「以拆分超长对话",
            )
            if len(candidates) >= 3:
                break

        return self._dedupe(candidates)

    @staticmethod
    def _dedupe(candidates: List[CorrectionCandidate]) -> List[CorrectionCandidate]:
        seen: set[tuple[int, int, str]] = set()
        result: list[CorrectionCandidate] = []
        for candidate in candidates:
            key = (candidate.start_offset, candidate.end_offset, candidate.replacement)
            if key in seen:
                continue
            seen.add(key)
            result.append(
                CorrectionCandidate(
                    candidate_id=f"c{len(result) + 1}",
                    error_id=candidate.error_id,
                    error_type=candidate.error_type,
                    start_offset=candidate.start_offset,
                    end_offset=candidate.end_offset,
                    replacement=candidate.replacement,
                    description=candidate.description,
                )
            )
        return result
